/*
 * master_hw.h
 *
 *  Created on: Jul 28, 2021
 *      Author: KhanhDinh
 */

#ifndef BOARD_STM32_RS485_BSP_MASTER_HW_MASTER_HW_H_
#define BOARD_STM32_RS485_BSP_MASTER_HW_MASTER_HW_H_

#include "compiler_optimize.h"
#include "stm32f1xx_hal.h"

#define MASTER_LED_PORT				GPIOB
#define MASTER_LED1_PIN				GPIO_PIN_15
#define MASTER_LED2_PIN				GPIO_PIN_14
#define MASTER_LED3_PIN				GPIO_PIN_13
#define MASTER_LED4_PIN				GPIO_PIN_12

#define MASTER_LED1_SET_HIGH		HAL_GPIO_WritePin(MASTER_LED_PORT, MASTER_LED1_PIN, GPIO_PIN_SET)
#define MASTER_LED2_SET_HIGH		HAL_GPIO_WritePin(MASTER_LED_PORT, MASTER_LED2_PIN, GPIO_PIN_SET)
#define MASTER_LED3_SET_HIGH		HAL_GPIO_WritePin(MASTER_LED_PORT, MASTER_LED3_PIN, GPIO_PIN_SET)
#define MASTER_LED4_SET_HIGH		HAL_GPIO_WritePin(MASTER_LED_PORT, MASTER_LED4_PIN, GPIO_PIN_SET)
#define MASTER_LED1_SET_LOW			HAL_GPIO_WritePin(MASTER_LED_PORT, MASTER_LED1_PIN, GPIO_PIN_RESET)
#define MASTER_LED2_SET_LOW			HAL_GPIO_WritePin(MASTER_LED_PORT, MASTER_LED2_PIN, GPIO_PIN_RESET)
#define MASTER_LED3_SET_LOW			HAL_GPIO_WritePin(MASTER_LED_PORT, MASTER_LED3_PIN, GPIO_PIN_RESET)
#define MASTER_LED4_SET_LOW			HAL_GPIO_WritePin(MASTER_LED_PORT, MASTER_LED4_PIN, GPIO_PIN_RESET)

void master_hw_init(void);

#endif /* BOARD_STM32_RS485_BSP_MASTER_HW_MASTER_HW_H_ */
