/*
 * master_hw.h
 *
 *  Created on: Jul 28, 2021
 *      Author: KhanhDinh
 */

#ifndef BOARD_STM32_RS485_BSP_MASTER_HW_MASTER_HW_H_
#define BOARD_STM32_RS485_BSP_MASTER_HW_MASTER_HW_H_

#include "compiler_optimize.h"
#include "stm32f1xx_hal.h"

#define BSS_LED_PORT				GPIOB
#define BSS_LED_CTRL_PIN				GPIO_PIN_15
#define BSS_LED_RED_PIN				GPIO_PIN_14
#define BSS_LED_BLUE_PIN			GPIO_PIN_13
#define BSS_LED_GREEN_PIN			GPIO_PIN_12

#define BSS_LED_ENABLE				HAL_GPIO_WritePin(BSS_LED_PORT, BSS_LED_CTRL_PIN, GPIO_PIN_SET)
#define BSS_LED_RED_SET_HIGH		HAL_GPIO_WritePin(BSS_LED_PORT, BSS_LED_RED_PIN, GPIO_PIN_SET)
#define BSS_LED_BLUE_SET_HIGH		HAL_GPIO_WritePin(BSS_LED_PORT, BSS_LED_BLUE_PIN, GPIO_PIN_SET)
#define BSS_LED_GREEN_SET_HIGH		HAL_GPIO_WritePin(BSS_LED_PORT, BSS_LED_GREEN_PIN, GPIO_PIN_SET)
#define BSS_LED_DISABLE				HAL_GPIO_WritePin(BSS_LED_PORT, BSS_LED_CTRL_PIN, GPIO_PIN_RESET)
#define BSS_LED_RED_SET_LOW			HAL_GPIO_WritePin(BSS_LED_PORT, BSS_LED_RED_PIN, GPIO_PIN_RESET)
#define BSS_LED_BLUE_SET_LOW		HAL_GPIO_WritePin(BSS_LED_PORT, BSS_LED_BLUE_PIN, GPIO_PIN_RESET)
#define BSS_LED_GREEN_SET_LOW		HAL_GPIO_WritePin(BSS_LED_PORT, BSS_LED_GREEN_PIN, GPIO_PIN_RESET)

void master_hw_init(void);

#endif /* BOARD_STM32_RS485_BSP_MASTER_HW_MASTER_HW_H_ */
